name: stockmanager
description: A Flutter application for inventory management.
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.11
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.4.0 
  google_fonts: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  hive_generator: ^2.0.0
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1 

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icono.png" 
